version: '3'

services:
    bot:
        image: ghcr.io/cielneko/quote-bot
        env_file: .env-bot
        restart: always
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "3"
        networks:
            - quotly
        command: node index.js
        volumes:
            - ./config:/app/config
    mongo:
        restart: always
        image: mongo:4.4.6
        volumes:
            - ./data/db:/data/db
        networks:
            - quotly
    api:
        image: ghcr.io/cielneko/quote-api
        env_file: .env-api
        restart: always
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "3"
        volumes:
            - ./fonts:/app/assets/fonts
            - /usr/local/share/fonts:/usr/local/shre/fonts:ro
            - /usr/share/fonts:/usr/share/fonts:ro
        networks:
            - quotly
        command: node index.js

networks:
    quotly:
        
